### PR TITLE
Refactor distributed lock, such that they work with async code

### PR DESCRIPTION
**Pull request by Spacefish**
- Changed the locks from `Monitor` to `SemaphoreSlim` which works in async contexts, where the lock is acquired by one thread and released by another
- Moved the lock handling to the `MemoryStorageConnection` class to avoid spreading state over multiple types
- Added an `Disposable` Utillity class to have a quickhand for returning disposables

### CODE REVIEW

**Comment by perrich** [comment]
Thank you, I'll try to check and merge your PR tomorrow.

**Comment by perrich** [comment]
Thanks, seems to work well (not reproduced the sync issue from #31)

**Comment by EvheniyHlushko** [comment]
```
`Hangfire.Storage.DistributedLockTimeoutException
Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'lock:recurring-job:Test' resource.
   at Hangfire.MemoryStorage.MemoryStorageConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.RecurringJobExtensions.AcquireDistributedRecurringJobLock(IStorageConnection connection, String recurringJobId, TimeSpan timeout)
   at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options)
   at Hangfire.RecurringJobManagerExtensions.AddOrUpdate[T](IRecurringJobManager manager, String recurringJobId, Expression`1 methodCall, String cronExpression, RecurringJobOptions options)
   at Hangfire.RecurringJobManagerExtensions.AddOrUpdate[T](IRecurringJobManager manager, String recurringJobId, Expression`1 methodCall, Func`1 cronExpression, RecurringJobOptions options)`
```


Looks like after these changes on version 1.8  encountering test failures when run in parallel. Everything works in the previous version, 1.7.0.

**Comment by perrich** [comment]
Seems that you try to execute same named job in the same time. First is not finished and second request is in timeout.
I don't think it's a bug.

**Comment by EvheniyHlushko** [comment]
Right. I'm using WebApplicationFactory for tests. In Strartup each instance adds a background job. Probably it's because Data are stored in a static way

**Comment by Spacefish** [comment]
> Right. I'm using WebApplicationFactory for tests. In Strartup each instance adds a background job. Probably it's because Data are stored in a static way

yes it uses static variables to store a lot of internal state.. So no separation between different instances.. I tried to make them independant while fixing this synchronization issue, but it would have introduced too many changes, as some other code relies on different instances of this jobmanager to access the same underlying data.. 

You would have to refactor a lot more to keep isolation between objects and still keep it functional..

**Comment by EvheniyHlushko** [comment]
Built a package based on your PR, still encountering the same issue.

> Furthemore Hangfire itself uses static classes / advertises the use of static class methods to submit jobs..

Most likely it's the case

**Pull request merged**
